//! Oracle test (kr0ki#12 checklist item 5; `docs/EVAL-kubediagrams.md` §2(c)):
//! differential-validate [`kr0ki_core::k8s_recognizer::KubernetesRecognizer`]
//! against a *real* KubeDiagrams `dot_json` render.
//!
//! No live KubeDiagrams/Python/Graphviz install is needed to run this: the
//! input manifests and the oracle's `dot_json` output are both already
//! vendored in `vendor/kubediagrams` (a git submodule), generated by
//! KubeDiagrams' own `examples/online-boutique/generate.sh` from the real
//! Google Cloud microservices-demo release manifests. If that submodule
//! isn't checked out, both tests are skipped with an explanatory message
//! rather than failing the whole suite.
//!
//! This does **not** assert full recall over KubeDiagrams' whole ~51-kind
//! catalogue — `k8s_recognizer.rs`'s module docs list what's ported vs.
//! deliberately deferred, and this fixture happens to exercise exactly two
//! of the ported categories (`Deployment` -> `ServiceAccount` via
//! `serviceAccountName`, `Service` -> `Deployment` via label selection).
//! Two properties are checked instead: **precision** (every edge kr0ki's
//! recognizer emits also appears in the oracle — kr0ki never invents a
//! relationship KubeDiagrams doesn't also see) and **recall within those two
//! supported categories** (kr0ki finds every oracle edge of those kinds).

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use kr0ki_core::k8s_recognizer::KubernetesRecognizer;
use serde::Deserialize;
use serde_json::Value;

fn fixture_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../vendor/kubediagrams/examples/online-boutique")
}

/// `Some(root)` if the vendored fixtures are present, else `None` (submodule
/// not checked out — skip rather than fail).
fn fixtures() -> Option<(PathBuf, PathBuf)> {
    let root = fixture_root();
    let manifests = root.join("downloads/online-boutique-manifests.yaml");
    let dot_json = root.join("diagrams/online-boutique-manifests.dot_json");
    if manifests.is_file() && dot_json.is_file() {
        Some((manifests, dot_json))
    } else {
        None
    }
}

fn load_manifests(path: &Path) -> Vec<Value> {
    let text =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    serde_yaml::Deserializer::from_str(&text)
        .map(|doc| {
            let yv = serde_yaml::Value::deserialize(doc).expect("valid YAML document");
            serde_json::to_value(&yv).expect("YAML value converts to JSON value")
        })
        .filter(|v| !v.is_null())
        .collect()
}

fn load_dot_json(path: &Path) -> Value {
    let text =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    serde_json::from_str(&text).expect("valid dot_json")
}

/// `(kind, name)` for every real k8s-object node in the oracle's `dot_json`,
/// keyed by its `objects[]` index. Cluster/`Application:` subgraph
/// pseudo-nodes (whose `tooltip` doesn't start with `"kind:"`) become `None`.
fn oracle_object_kind_names(dot_json: &Value) -> Vec<Option<(String, String)>> {
    dot_json
        .get("objects")
        .and_then(Value::as_array)
        .expect("dot_json objects array")
        .iter()
        .map(|o| {
            let tooltip = o.get("tooltip")?.as_str()?;
            if !tooltip.starts_with("kind:") {
                return None;
            }
            let kind = tooltip.lines().next()?.strip_prefix("kind: ")?.to_string();
            let name = tooltip
                .lines()
                .find_map(|l| l.trim_start().strip_prefix("name:"))?
                .trim()
                .to_string();
            Some((kind, name))
        })
        .collect()
}

/// Every `(source_kind, source_name, target_kind, target_name)` edge in the
/// oracle's `dot_json`, resolved from its `tail`/`head` object indices.
fn oracle_edges(dot_json: &Value) -> HashSet<(String, String, String, String)> {
    let objects = oracle_object_kind_names(dot_json);
    dot_json
        .get("edges")
        .and_then(Value::as_array)
        .expect("dot_json edges array")
        .iter()
        .filter_map(|e| {
            let tail = e.get("tail")?.as_u64()? as usize;
            let head = e.get("head")?.as_u64()? as usize;
            let (tk, tn) = objects.get(tail)?.clone()?;
            let (hk, hn) = objects.get(head)?.clone()?;
            Some((tk, tn, hk, hn))
        })
        .collect()
}

/// kr0ki's `ElementId` is `"k8s:{namespace|-}/{kind}/{name}"`
/// (`k8s_recognizer.rs::element_id`) — recover `(kind, name)` to compare
/// against the oracle's own `(kind, name)` pairs.
fn kind_name(id: &str) -> (String, String) {
    let rest = id.strip_prefix("k8s:").expect("kr0ki k8s ElementId");
    let mut parts = rest.splitn(3, '/');
    let _namespace = parts.next().expect("namespace segment");
    let kind = parts.next().expect("kind segment").to_string();
    let name = parts.next().expect("name segment").to_string();
    (kind, name)
}

#[test]
fn kr0ki_recognizer_edges_are_all_confirmed_by_the_kubediagrams_oracle() {
    let Some((manifests_path, dot_json_path)) = fixtures() else {
        eprintln!("skipping: vendor/kubediagrams submodule not checked out");
        return;
    };
    let manifests = load_manifests(&manifests_path);
    assert!(!manifests.is_empty(), "fixture manifests must not be empty");

    let dot_json = load_dot_json(&dot_json_path);
    let oracle = oracle_edges(&dot_json);
    assert!(!oracle.is_empty(), "fixture oracle must have edges");

    let edges = KubernetesRecognizer::new().recognize(&manifests);
    assert!(
        !edges.is_empty(),
        "recognizer should find edges in this fixture"
    );

    for e in &edges {
        let (sk, sn) = kind_name(e.source.as_str());
        let (tk, tn) = kind_name(e.target.as_str());
        let forward = (sk.clone(), sn.clone(), tk.clone(), tn.clone());
        let backward = (tk, tn, sk, sn);
        assert!(
            oracle.contains(&forward) || oracle.contains(&backward),
            "kr0ki edge {forward:?} (relation {:?}) has no corresponding edge in the \
             KubeDiagrams oracle — the recognizer may be inventing a relationship",
            e.relation
        );
    }
}

#[test]
fn kr0ki_recognizer_recovers_every_oracle_edge_in_its_supported_categories() {
    let Some((manifests_path, dot_json_path)) = fixtures() else {
        eprintln!("skipping: vendor/kubediagrams submodule not checked out");
        return;
    };
    let manifests = load_manifests(&manifests_path);
    let dot_json = load_dot_json(&dot_json_path);
    let oracle = oracle_edges(&dot_json);

    // Scoped to exactly the two edge families this fixture's oracle exercises,
    // both of which k8s_recognizer.rs documents as supported — not a claim of
    // full recall over KubeDiagrams' whole catalogue.
    let supported_oracle_edges: Vec<_> = oracle
        .iter()
        .filter(|(sk, _, tk, _)| {
            (sk == "Deployment" && tk == "ServiceAccount")
                || (sk == "Service" && tk == "Deployment")
        })
        .collect();
    assert_eq!(
        supported_oracle_edges.len(),
        23,
        "sanity check on this fixture's known edge count — if this fails, the vendored \
         oracle fixture changed and the test needs re-grounding, not a bumped number"
    );

    let edges = KubernetesRecognizer::new().recognize(&manifests);
    let found: HashSet<_> = edges
        .iter()
        .map(|e| {
            let (sk, sn) = kind_name(e.source.as_str());
            let (tk, tn) = kind_name(e.target.as_str());
            (sk, sn, tk, tn)
        })
        .collect();

    for want in supported_oracle_edges {
        assert!(
            found.contains(want),
            "expected kr0ki to recover oracle edge {want:?}"
        );
    }
}
