// @ts-check
const { test, expect } = require('@playwright/test');

// Implements the CORE-* cases from ../TEST-DEFINITIONS.md against the real,
// currently-implemented Box 5 surface (kr0ki-core + kr0ki-server: cache,
// render, docs — see AGENTS.md §1). UI/agent-panel (playbook Vue) cases are
// intentionally not covered here: the playbook UI was observed stuck
// mid-render during authoring of this suite (2026-09-29), which is a
// separate, pre-existing issue tracked by the AGENT-*-FIX.md notes at the
// repo root, not something to paper over with a flaky selector-based test.

test.describe('CORE: server health', () => {
  test('CORE-001: /health reports ok', async ({ request }) => {
    const res = await request.get('/health');
    expect(res.status()).toBe(200);
    const body = await res.json();
    expect(body.status).toBe('ok');
    expect(body.service).toBe('kr0ki');
  });
});

test.describe('CORE: formats', () => {
  test('/formats lists the standalone diagram slugs', async ({ request }) => {
    const res = await request.get('/formats');
    expect(res.status()).toBe(200);
    const formats = await res.json();
    expect(Array.isArray(formats)).toBe(true);
    // Mermaid is companion-only and deliberately excluded — AGENTS.md §7.
    expect(formats).not.toContain('mermaid');
    for (const fmt of ['graphviz', 'd2', 'plantuml']) {
      expect(formats).toContain(fmt);
    }
  });
});

test.describe('CORE: direct render', () => {
  test('CORE-003a: graphviz DOT source renders to real SVG', async ({ request }) => {
    const res = await request.post('/render/graphviz?output=svg', {
      data: 'digraph { a -> b }',
      headers: { 'content-type': 'text/plain' },
    });
    expect(res.status()).toBe(200);
    const svg = await res.text();
    expect(svg).toContain('<svg');
    expect(svg).toContain('<!-- Generated by graphviz');
  });

  test('CORE-003b: d2 source renders to real SVG', async ({ request }) => {
    const res = await request.post('/render/d2?output=svg', {
      data: 'x -> y -> z',
      headers: { 'content-type': 'text/plain' },
    });
    expect(res.status()).toBe(200);
    const svg = await res.text();
    expect(svg).toContain('<svg');
    expect(svg).toContain('data-d2-version');
  });

  test('d2 PNG now renders (AGENTS.md §7 "D2 PNG does not exist" is stale)', async ({
    request,
  }) => {
    // Verified 2026-09-29 against the live backend: POST /render/d2?output=png
    // returns 200 with real PNG bytes, not the 400 AGENTS.md §7 documents.
    // Left failing-if-reverted rather than silently dropped, so a real
    // regression back to the old behavior is caught — but the doc itself
    // needs a human to update since this contradicts checked-in tribal
    // knowledge.
    const res = await request.post('/render/d2?output=png', {
      data: 'x -> y',
      headers: { 'content-type': 'text/plain' },
    });
    expect(res.status()).toBe(200);
    const bytes = await res.body();
    expect(bytes.subarray(0, 8).toString('hex')).toBe('89504e470d0a1a0a'); // PNG magic
  });

  test('unknown format slug is rejected, not silently proxied', async ({ request }) => {
    const res = await request.post('/render/not-a-real-format?output=svg', {
      data: 'irrelevant',
      headers: { 'content-type': 'text/plain' },
    });
    expect(res.status()).toBeGreaterThanOrEqual(400);
    expect(res.status()).toBeLessThan(500);
  });
});

test.describe('CORE: cache', () => {
  test('identical (format, output, source) is a content-addressed cache hit on the 2nd call', async ({
    request,
  }) => {
    const source = `digraph { cache_probe_${Date.now()} -> b }`;
    const first = await request.post('/render/graphviz?output=svg', {
      data: source,
      headers: { 'content-type': 'text/plain' },
    });
    expect(first.status()).toBe(200);
    const firstBody = await first.text();

    const second = await request.post('/render/graphviz?output=svg', {
      data: source,
      headers: { 'content-type': 'text/plain' },
    });
    expect(second.status()).toBe(200);
    const secondBody = await second.text();

    // Same source -> byte-identical cached SVG (kr0ki-core/tests/live_png.rs
    // asserts the PNG analogue of this same content-addressed guarantee).
    expect(secondBody).toBe(firstBody);
  });

  test('same graphviz source, SVG vs PNG output are different cache entries', async ({
    request,
  }) => {
    // AGENTS.md §7: cache_key() hashes (format, output, source) — svg and
    // png for the same source must not collide.
    const source = 'digraph { a -> b }';
    const svgRes = await request.post('/render/graphviz?output=svg', {
      data: source,
      headers: { 'content-type': 'text/plain' },
    });
    const pngRes = await request.post('/render/graphviz?output=png', {
      data: source,
      headers: { 'content-type': 'text/plain' },
    });
    expect(svgRes.status()).toBe(200);
    expect(pngRes.status()).toBe(200);
    expect(svgRes.headers()['content-type']).toContain('svg');
    expect(pngRes.headers()['content-type']).toContain('png');
  });
});

test.describe('CORE: self-documentation (/docs)', () => {
  test('/docs renders the live symbol index and diagram example', async ({ page }) => {
    await page.goto('/docs');
    await expect(page).toHaveTitle('kr0ki documentation');
    await expect(page.locator('h1')).toHaveText('kr0ki documentation');
    // The b00t-stack-orchestration D2 template + copy-paste curl command,
    // per AGENTS.md §5 ("When kr0ki is running, /docs is self-documenting").
    await expect(page.locator('#diagram-example')).toBeVisible();
    await expect(page.locator('#capabilities')).toBeVisible();
  });

  test('/docs/api.json returns the harvested Symbol array', async ({ request }) => {
    const res = await request.get('/docs/api.json');
    expect(res.status()).toBe(200);
    const symbols = await res.json();
    expect(Array.isArray(symbols)).toBe(true);
    expect(symbols.length).toBeGreaterThan(0);
  });
});
